### ISSUE TITLE
Missing PhysicalBallotStyle instances in BallotStyle class definition

### ISSUE THREAD

**Issue by carl3** [usnistgov/BallotDefinition#4]
The BallotStyle Class documentation says "BallotStyle references zero or more PhysicalBallotStyle instances for describing physical manifestations of the ballot style.", but there is no such element in the class and no class definition.

If PhysicalBallotStyle is a future addition, add the reference and a dummy class definition with documentation indicating
the intended content.

If legacy documentation that no longer applies, remove it.

**Comment by JDziurlaj** [comment]
It has been removed, as all its properties have been moved into `BallotFormat`. I will update the documentation.
